package com.example.demo.entity;
// Generated 28 ago 2025, 15:07:26 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * BorsaDiStudio generated by hbm2java
 */
public class BorsaDiStudio implements java.io.Serializable {

	private int id;
	private TipologiaBorsa tipologiaBorsa;
	private String programma;
	private String enteFinanziario;
	private String annoAccademico;
	private Set domandaBorsaDiStudios = new HashSet(0);
	private Set studentes = new HashSet(0);

	public BorsaDiStudio() {
	}

	public BorsaDiStudio(int id, String programma, String enteFinanziario, String annoAccademico) {
		this.id = id;
		this.programma = programma;
		this.enteFinanziario = enteFinanziario;
		this.annoAccademico = annoAccademico;
	}

	public BorsaDiStudio(int id, TipologiaBorsa tipologiaBorsa, String programma, String enteFinanziario,
			String annoAccademico, Set domandaBorsaDiStudios, Set studentes) {
		this.id = id;
		this.tipologiaBorsa = tipologiaBorsa;
		this.programma = programma;
		this.enteFinanziario = enteFinanziario;
		this.annoAccademico = annoAccademico;
		this.domandaBorsaDiStudios = domandaBorsaDiStudios;
		this.studentes = studentes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TipologiaBorsa getTipologiaBorsa() {
		return this.tipologiaBorsa;
	}

	public void setTipologiaBorsa(TipologiaBorsa tipologiaBorsa) {
		this.tipologiaBorsa = tipologiaBorsa;
	}

	public String getProgramma() {
		return this.programma;
	}

	public void setProgramma(String programma) {
		this.programma = programma;
	}

	public String getEnteFinanziario() {
		return this.enteFinanziario;
	}

	public void setEnteFinanziario(String enteFinanziario) {
		this.enteFinanziario = enteFinanziario;
	}

	public String getAnnoAccademico() {
		return this.annoAccademico;
	}

	public void setAnnoAccademico(String annoAccademico) {
		this.annoAccademico = annoAccademico;
	}

	public Set getDomandaBorsaDiStudios() {
		return this.domandaBorsaDiStudios;
	}

	public void setDomandaBorsaDiStudios(Set domandaBorsaDiStudios) {
		this.domandaBorsaDiStudios = domandaBorsaDiStudios;
	}

	public Set getStudentes() {
		return this.studentes;
	}

	public void setStudentes(Set studentes) {
		this.studentes = studentes;
	}

}
