package com.example.demo.entity;
// Generated 28 ago 2025, 15:07:26 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;


import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;

/**
 * BorsaDiStudio generated by hbm2java
 */
@Entity
public class BorsaDiStudio implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipologia_borsa_id", nullable = false)
	private TipologiaBorsa tipologiaBorsa;
	private String programma;
	private String enteFinanziario;
	private String annoAccademico;
	@OneToMany(mappedBy = "borsaDiStudio", cascade = CascadeType.ALL , fetch = FetchType.LAZY)
	private Set<DomandaBorsaDiStudio> domandaBorsaDiStudios = new HashSet<>();
	@OneToMany(mappedBy = "borsaDiStudio", fetch = FetchType.LAZY)
	private Set<Studente> studentes = new HashSet<>();

	public BorsaDiStudio() {
	}

	public BorsaDiStudio(int id, String programma, String enteFinanziario, String annoAccademico) {
		this.id = id;
		this.programma = programma;
		this.enteFinanziario = enteFinanziario;
		this.annoAccademico = annoAccademico;
	}

	public BorsaDiStudio(int id, TipologiaBorsa tipologiaBorsa, String programma, String enteFinanziario,
			String annoAccademico, Set<DomandaBorsaDiStudio> domandaBorsaDiStudios, Set<Studente> studentes) {
		this.id = id;
		this.tipologiaBorsa = tipologiaBorsa;
		this.programma = programma;
		this.enteFinanziario = enteFinanziario;
		this.annoAccademico = annoAccademico;
		this.domandaBorsaDiStudios = domandaBorsaDiStudios;
		this.studentes = studentes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TipologiaBorsa getTipologiaBorsa() {
		return this.tipologiaBorsa;
	}

	public void setTipologiaBorsa(TipologiaBorsa tipologiaBorsa) {
		this.tipologiaBorsa = tipologiaBorsa;
	}

	public String getProgramma() {
		return this.programma;
	}

	public void setProgramma(String programma) {
		this.programma = programma;
	}

	public String getEnteFinanziario() {
		return this.enteFinanziario;
	}

	public void setEnteFinanziario(String enteFinanziario) {
		this.enteFinanziario = enteFinanziario;
	}

	public String getAnnoAccademico() {
		return this.annoAccademico;
	}

	public void setAnnoAccademico(String annoAccademico) {
		this.annoAccademico = annoAccademico;
	}

	public Set getDomandaBorsaDiStudios() {
		return this.domandaBorsaDiStudios;
	}

	public void setDomandaBorsaDiStudios(Set<DomandaBorsaDiStudio> domandaBorsaDiStudios) {
		this.domandaBorsaDiStudios = domandaBorsaDiStudios;
	}

	public Set getStudentes() {
		return this.studentes;
	}

	public void setStudentes(Set<Studente> studentes) {
		this.studentes = studentes;
	}

}
