
package com.example.demo.entity;
// Generated 28 ago 2025, 15:07:26 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * DomandaBorsaDiStudio generated by hbm2java
 */
@Entity
public class DomandaBorsaDiStudio implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private Studente studente;
	private BorsaDiStudio borsaDiStudio;
	private Date dataInvio;
	private String universitaEstera;
	private Date dataInizioSoggiornoEstero;
	private Date dataFineSoggiornoEstero;

	public DomandaBorsaDiStudio() {
	}

	public DomandaBorsaDiStudio(int id, Date dataInvio) {
		this.id = id;
		this.dataInvio = dataInvio;
	}

	public DomandaBorsaDiStudio(int id, Studente studente, BorsaDiStudio borsaDiStudio, Date dataInvio,
			String universitaEstera, Date dataInizioSoggiornoEstero, Date dataFineSoggiornoEstero) {
		this.id = id;
		this.studente = studente;
		this.borsaDiStudio = borsaDiStudio;
		this.dataInvio = dataInvio;
		this.universitaEstera = universitaEstera;
		this.dataInizioSoggiornoEstero = dataInizioSoggiornoEstero;
		this.dataFineSoggiornoEstero = dataFineSoggiornoEstero;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Studente getStudente() {
		return this.studente;
	}

	public void setStudente(Studente studente) {
		this.studente = studente;
	}

	public BorsaDiStudio getBorsaDiStudio() {
		return this.borsaDiStudio;
	}

	public void setBorsaDiStudio(BorsaDiStudio borsaDiStudio) {
		this.borsaDiStudio = borsaDiStudio;
	}

	public Date getDataInvio() {
		return this.dataInvio;
	}

	public void setDataInvio(Date dataInvio) {
		this.dataInvio = dataInvio;
	}

	public String getUniversitaEstera() {
		return this.universitaEstera;
	}

	public void setUniversitaEstera(String universitaEstera) {
		this.universitaEstera = universitaEstera;
	}

	public Date getDataInizioSoggiornoEstero() {
		return this.dataInizioSoggiornoEstero;
	}

	public void setDataInizioSoggiornoEstero(Date dataInizioSoggiornoEstero) {
		this.dataInizioSoggiornoEstero = dataInizioSoggiornoEstero;
	}

	public Date getDataFineSoggiornoEstero() {
		return this.dataFineSoggiornoEstero;
	}

	public void setDataFineSoggiornoEstero(Date dataFineSoggiornoEstero) {
		this.dataFineSoggiornoEstero = dataFineSoggiornoEstero;
	}

}
