package com.example.demo.entity;
// Generated 28 ago 2025, 15:07:26 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;

/**
 * Studente generated by hbm2java
 */
@Entity
public class Studente implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "borsa_di_studio_id", nullable = true)
	private BorsaDiStudio borsaDiStudio;
	private String nome;
	private String cognome;
	private String matricola;
	private Integer mediaVoti;
	private Integer isee;
	private Boolean erasmus;
	@OneToMany(mappedBy = "studente", fetch = FetchType.LAZY)
	private Set<DomandaBorsaDiStudio> domandaBorsaDiStudios = new HashSet<>();

	public Studente() {
	}

	public Studente(int id, String nome, String cognome, String matricola) {
		this.id = id;
		this.nome = nome;
		this.cognome = cognome;
		this.matricola = matricola;
	}

	public Studente(int id, BorsaDiStudio borsaDiStudio, String nome, String cognome, String matricola,
			Integer mediaVoti, Integer isee, Boolean erasmus, Set<DomandaBorsaDiStudio> domandaBorsaDiStudios) {
		this.id = id;
		this.borsaDiStudio = borsaDiStudio;
		this.nome = nome;
		this.cognome = cognome;
		this.matricola = matricola;
		this.mediaVoti = mediaVoti;
		this.isee = isee;
		this.erasmus = erasmus;
		this.domandaBorsaDiStudios = domandaBorsaDiStudios;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public BorsaDiStudio getBorsaDiStudio() {
		return this.borsaDiStudio;
	}

	public void setBorsaDiStudio(BorsaDiStudio borsaDiStudio) {
		this.borsaDiStudio = borsaDiStudio;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getMatricola() {
		return this.matricola;
	}

	public void setMatricola(String matricola) {
		this.matricola = matricola;
	}

	public Integer getMediaVoti() {
		return this.mediaVoti;
	}

	public void setMediaVoti(Integer mediaVoti) {
		this.mediaVoti = mediaVoti;
	}

	public Integer getIsee() {
		return this.isee;
	}

	public void setIsee(Integer isee) {
		this.isee = isee;
	}

	public Boolean getErasmus() {
		return this.erasmus;
	}

	public void setErasmus(Boolean erasmus) {
		this.erasmus = erasmus;
	}

	public Set<DomandaBorsaDiStudio> getDomandaBorsaDiStudios() {
		return this.domandaBorsaDiStudios;
	}

	public void setDomandaBorsaDiStudios(Set<DomandaBorsaDiStudio> domandaBorsaDiStudios) {
		this.domandaBorsaDiStudios = domandaBorsaDiStudios;
	}

}
