package com.example.demo.entity;
// Generated 28 ago 2025, 15:07:26 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;

/**
 * TipologiaBorsa generated by hbm2java
 */
@Entity
public class TipologiaBorsa implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private String nomeTipologia;
	private Integer sogliaIsee;
	private Integer mediaMinima;
	private String modalitaErogazione;
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "borsa_di_studio", nullable = false)
	private Set<BorsaDiStudio> borsaDiStudios = new HashSet<>();

	public TipologiaBorsa() {
	}

	public TipologiaBorsa(int id, String nomeTipologia, String modalitaErogazione) {
		this.id = id;
		this.nomeTipologia = nomeTipologia;
		this.modalitaErogazione = modalitaErogazione;
	}

	public TipologiaBorsa(int id, String nomeTipologia, Integer sogliaIsee, Integer mediaMinima,
			String modalitaErogazione, Set<BorsaDiStudio> borsaDiStudios) {
		this.id = id;
		this.nomeTipologia = nomeTipologia;
		this.sogliaIsee = sogliaIsee;
		this.mediaMinima = mediaMinima;
		this.modalitaErogazione = modalitaErogazione;
		this.borsaDiStudios = borsaDiStudios;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNomeTipologia() {
		return this.nomeTipologia;
	}

	public void setNomeTipologia(String nomeTipologia) {
		this.nomeTipologia = nomeTipologia;
	}

	public Integer getSogliaIsee() {
		return this.sogliaIsee;
	}

	public void setSogliaIsee(Integer sogliaIsee) {
		this.sogliaIsee = sogliaIsee;
	}

	public Integer getMediaMinima() {
		return this.mediaMinima;
	}

	public void setMediaMinima(Integer mediaMinima) {
		this.mediaMinima = mediaMinima;
	}

	public String getModalitaErogazione() {
		return this.modalitaErogazione;
	}

	public void setModalitaErogazione(String modalitaErogazione) {
		this.modalitaErogazione = modalitaErogazione;
	}

	public Set getBorsaDiStudios() {
		return this.borsaDiStudios;
	}

	public void setBorsaDiStudios(Set<BorsaDiStudio> borsaDiStudios) {
		this.borsaDiStudios = borsaDiStudios;
	}

}
